### ISSUE TITLE
Export (and use) resolveInclude

### ISSUE THREAD

**Issue by dresende** [tj/ejs#170]
If this function could be exported (to be replaced), I (and others) could overwrite it to be able to dynamically accept other include paths and possibly other crazy stuff. I had to do this and to achieve it I had to replace exports.parse (without changing it) to then be able to create my own `resolveInclude`.

This is just a tiny cool feature, not that I can't live without it..

**Comment by TimothyGu** [comment]
This is now tracked at mde/ejs#44.
