### ISSUE TITLE
Can't 'include' within <head> tags.

### ISSUE THREAD

**Issue by robotogre** [tj/ejs#176]
If I do the following within index.html:

```html
<head>
     {{ include commonHead.html }}
</head>
<body>
</body>
```

The rendered version of index.html that is served appears as:

```html
<head>
</head>
<body>
     "    "
     <meta name="viewport" content="width=device-width, initial-scale=1">
<meta
</body>
```

Two things are wrong:

1. The included content should have been written inside the 'head' tags. NOT the 'body' tags...
2. A strange empty string was added after the 'body' tag. : "     "

How can I 'include' text inside the 'head' tags? :(

**Comment by TimothyGu** [comment]
@robotogre Can you answer @ForbesLindesay's two questions? I really want to fix this, so if you are still here please give us enough information to reproduce this bug.

**Comment by robotogre** [comment]
Hello! I have searched my computer, but I am unable to find the affected code project files. :(

I would assume that the problem was almost certainly my fault, as I am a total novice with node.js and JavaScript templating engines.

I am extremely impressed with your intent to help!
