### ISSUE TITLE
Web server version

### ISSUE THREAD

**Issue by isaacrg** [tj/ejs#180]
An optimistic request, rather, but could there be a version of EJS which supports PHP style executable file, where each template can be executed on its own.

**Comment by TimothyGu** [comment]
Unlikely. EJS is for templating only, unlike PHP.

**Comment by ir-g** [comment]
@TimothyGu Ok. I may write an experimental implementation of this suggestion.

**Comment by mde** [comment]
This seems to be very similar to what you're looking for: http://www.cgi-node.org/

**Comment by ir-g** [comment]
Not quite like that...I aim to create it entirely node-based.

**Comment by mde** [comment]
In any case, this seems to be outside the scope of this EJS project. I'm going to go ahead and close this issue.
