### ISSUE TITLE
How to break line within <%= here is a string %>

### ISSUE THREAD

**Issue by sebthiriet** [tj/ejs#187]
If I receive from my client a string with "Hello\nHow are you?"...

Then:

1) If I do the job to replace \n by <\br> then the string that appears on the browser is:

Hello<\br>How are you?

2) If I don't replace anything, then (of course :) the string in the browser is:

Hello\nHow are you?

So my question is: 
How you guys handle the line breaking without going to go for too complex code in .ejs placeholders?

Thanks, 

Sebastien

PS: <\br> is not the right html tag for break line, I write it like this to keep it displayed in this editor

**Comment by TimothyGu** [comment]
@sebthiriet Yes I would agree with @a2lin. Something like this should work:

``` js
<% var testVar = 'Line1\nLine2' %>
<%= testVar.replace('\n', '<br>') %>
```

**Comment by suriyanto** [comment]
@TimothyGu I don't think your example would work, as `<%=` ends up escaping `<br>` and display it. Any other suggestion that might help so we can use the ejs functionality?

**Comment by mde** [comment]
The solution here is to escape the content yourself before passing it to EJS, then use `<%- %>` for raw output:

``` javascript
var data = myOwnEscapeFunction(rawData);
var html;

data = data.replace(/\n/g, '<br/>');
html = ejs.render('<%- data %>', {data: data});
```

EJS actually includes an escape function -- maybe we should export it so people can use the same escape we use internally in cases like this.

**Comment by mde** [comment]
Can we close this issue? The raw output tags are the canonical solution for when you need to include your own HTML tags in rendered output. Seems like we're beating a dead horse here.

**Comment by suriyanto** [comment]
I must have missed something here. When I use `<%-`, it will show the escaped string with the unicode characters. For example, when I escape `a b`, then it becomes `a%20b`. When this is passed to `<%-`, it gets displayed in the view as `a%20b`.

![image](https://cloud.githubusercontent.com/assets/1008875/14231064/6b327da8-f942-11e5-8651-411d322a82d5.png)

Inspect element shows:
![image](https://cloud.githubusercontent.com/assets/1008875/14231066/9ed47dc8-f942-11e5-9230-1c701c53762e.png)

The .ejs snippet:

```
                <p class="description text-center">
                  <%- formatDisplay(profile.bio) %>
                </p>
```

The formatDisplay ejs function:

```
app.locals.formatDisplay = (para) => escape(para).replace(/%0D%0A/g, '<br>');
```

**Comment by mde** [comment]
We're not talking about the old, deprecated `escape` function in JavaScript. The original purpose of that function was to do URL-encoding:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape

It's not type of escaping we're talking about. (And the function is broken and deprecated even for its intended purpose.)

We are talking about sanitizing markup (you can search the Internet for "escape XML") to prevent cross-site scripting attacks. Here is more context about this:

https://www.owasp.org/index.php/XSS_%28Cross_Site_Scripting%29_Prevention_Cheat_Sheet

The part in question here is what that document calls "HTML Escape Before Inserting Untrusted Data into HTML Element Content."

**Comment by suriyanto** [comment]
@mde Thanks very much. Yes, I was using the deprecated JS function and completely got confused. It's all fine now after I change to use lodash escape function instead.

For future reference in case somebody encounter this in their search. The solution that I took:
- Add an EJS locals function:

```
let _ = require('lodash');
app.locals.htmlDisplay = html => _.escape(html).replace(/\n/g, '<br>');
```
- In the view, I simply do:

```
<%- htmlDisplay(stringToDisplay) %>
```

**Comment by apiconnectid1** [comment]
Can anyone help me to know that how we can send file data to HTML page using EJS. 1) I read the file successfully. 2)Take file data in var. 3)Send successfully to next ejs file using res.render with file data as parameter. 4)Revived successfully that parameter in ejs file.

Issue is When we use <% console.log(data)%> i am able to see exact file data with newline etc at console but if i use same inside <%= data>, all file behave as a string and print in one line. Example <% console.log(data)%>: Start working with Node JS. {temp purpose }

same data if used by <%= data>

Start working with Node JS. {temp purpose }

**Comment by mde** [comment]
This repo is no longer maintained. It is only here for historical interest. The current version of EJS can be found here: https://github.com/mde/ejs

**Comment by aymen94** [comment]
I used this
`text` is variable

` <%- text.replace(/\n/g, '<br/>') %>`

**Comment by blake-edwards** [comment]
> Have you tried the tag <%- %> instead of <%= %>?
> <%= escapes html by default (therefore your br tag is changed to it's escaped equivalent).

@a2lin This still is not working for me. Here is my EJS:
```
   <% for(var i=0; i < result.length; i++) { %>   
              <div class="card">
                  <h2><%= result[i].title %></h2>
                  <h5>Posted: <%= result[i].posted %></h5>
                  <p><%- result[i].body %></p>
              </div>
     <% } %>
```
Output example:
<img width="661" alt="screen shot 2018-09-15 at 2 36 24 am" src="https://user-images.githubusercontent.com/9518852/45583434-45c2dd00-b890-11e8-9ba4-b3889df2416f.png">


Can someone tell me why line breaks within the paragraph element do not work?  
I would eventually like to be able to write more HTML, other than simply break lines, if that can help anyone with a more accurate answer for my implementation. Thanks!

**Comment by mass85** [comment]
Answer to original question: you could leave the new line characters in string and use CSS `white-space: pre-wrap`. [https://stackoverflow.com/a/52482675/768438](https://stackoverflow.com/a/52482675/768438)

**Comment by Latyn** [comment]
If I do the job to replace \n by <\br> then the string that appears on the browser is:

**Comment by JettBurns14** [comment]
I'll leave my experiences with this issue and my solution for any future viewers.

Text messages from my database would be placed into the HTML of a page with EJS, but newlines wouldn't be displayed, even though I know they were there:
![Screen Shot 2019-04-11 at 10 03 46 PM](https://user-images.githubusercontent.com/24257648/56009554-c7071480-5ca5-11e9-8c0d-e2ac939900c4.png)

I tried the CSS `white-space: pre-wrap` method, which worked, but still left a huge space before the first sentence in my messages:
![Screen Shot 2019-04-11 at 9 50 37 PM](https://user-images.githubusercontent.com/24257648/56009022-e69d3d80-5ca3-11e9-84c9-c614d0b50293.png)

Then I tried replacing any `\n` in the messages with `<br>` with this code inside the EJS, which solved everything:
```<%- message.message_content.replace(/\n/g, '<br>') %>```
![Screen Shot 2019-04-11 at 9 54 39 PM](https://user-images.githubusercontent.com/24257648/56009161-7216ce80-5ca4-11e9-89bf-47f8b0808216.png)

Hope that helps somebody one day, and thank you @a2lin and @aymen94 for posting your above comments, they helped me figure this out.

**Comment by n3oney** [comment]
If you want escaping of any possible tags and still change \n to \<br>, then you should use this:
```
<%- content.replace(/\&+/g, "&amp;").replace(/\<+/g, "&lt;").replace(/\>+/g, "&gt;").replace(/\"+/g, "&quot;").replace(/\'+/g, "&#39;").replace(/\n+/g, "<br>") %>
```
This escapes every <, >, ', " and &, and then replaces the newlines with \<br>, so they actually don't get escaped.
[Preview](https://i.imgur.com/SlTbrat.png)

**Comment by cooljeffro** [comment]
You can also use `ejs.escapeXML` which ejs uses internally to escape HTML.

**Comment by tomasz-jankowski** [comment]
I know that 2 years have passed since the last answer but this might be helpful for others. Escaping HTML is a bad idea when it comes to a data which can be manipulated by users because of potentially dangerous JS code injection. Better idea would be to use below method:

```
<% for (const line of STRING.split("\n")) { %>
    <p><%= line %></p>
<% } %>
```

**Comment by jacob-leger** [comment]
> <img alt="@sebthiriet" width="40" height="40" src="https://avatars.githubusercontent.com/u/6012623?s=88&amp;v=4">

Thanks for the help!

**Comment by limitLam** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我暂时无法亲自回复您的邮件。我看到邮件后，尽快给您回复。

**Comment by Cream-colored** [comment]
@a2lin https://nodejser.space/questions/printing-cookies-in-the-ejs-view-engine-is-simple-and-easy-just-follow-these

**Comment by limitLam** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我暂时无法亲自回复您的邮件。我看到邮件后，尽快给您回复。
