### ISSUE TITLE
EJS on Client side ( Cordova / PhoneGap ) ?

### ISSUE THREAD

**Issue by efkan** [tj/ejs#195]
Hi,

Now I've been developing a Cordova application. 
How to use EJS on client side without node.js?

I want to create 3 part for my application. The parts are layout.ejs, homepage.ejs and user.ejs (subpage)

my layout EJS file

    <!DOCTYPE html>
    <html>
      <body>
        <%- body %>
      </body>
    </html>

my homepage EJS file

    <div>
        <p> Test contents </p>
        <% include user.ejs %>
       <h4> <%- user.username %> </h4>    
    </div>

**Comment by TimothyGu** [comment]
You can't `include` a file in the browser.

**Comment by efkan** [comment]
Thanks @TimothyGu
