### ISSUE TITLE
capitalize/upcase filter not working

### ISSUE THREAD

**Issue by techsolvr** [tj/ejs#202]
Following is my code which is displaying data correctly -

```
  <%= test %>
```

but whenever I try to capitalize or upper case my string its throwing error -

```
<%=: test | capitalize %>
<%=: test | upcase %>
```

I am sending data to the ejs template like- res.render({test: "bhgygygkggyggkygrdes"};

Let me know what I am doing wrong here.

FYI - I am using "ejs": "^2.3.1"

**Comment by mde** [comment]
This project is no longer active. The current EJS v2.x is here:

https://github.com/mde/ejs

Filters were removed in v2.x, so they are not expected to work.

**Comment by AmarPrabhu** [comment]
@mde is there any way I can continue using my existing filters from V1.x in V2 by creating my own objects for filters?

It was a very handy feature, why was it removed?
