### ISSUE TITLE
Cannot format output of toLocaleDateString

### ISSUE THREAD

**Issue by dgofman-equinix** [tj/ejs#205]
Based on documentation https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

We have an option for formatting output of Date object  I tried in my code using some options

<div><%= date.toLocaleDateString('en-US',  { year: 'numeric', month: 'long', day: 'numeric' }) %></div>

I am expecting a short string of date format "May 8, 2015"

But result is "Friday, May 08, 2015"

what is equal to this option:

new Date().toLocaleDateString('en-US',  { weekday: 'long', year: 'numeric', month: 'long', day: '2-digit' });

Can you please fix ASAP.

Thanks,
David

**Comment by mde** [comment]
This is nothing to do with EJS. EJS is just executing `toLocaleDateString` in whatever JS runtime you're  using. This returns different things based on what OS and JS runtime you have. If you want to ensure consistent formatting, use some sort of helper function or library.

**Comment by dgofman-equinix** [comment]
Hi Matthew,

I would like to know if your team can do soothing to help me for solving this issue.

https://github.com/tj/ejs/issues/207

I am using “nesting” template structure and I need to include into main template some dynamic resources from other templates.

Thanks,
David

**Comment by mde** [comment]
Sounds like you just want to use the `include` function conditionally. (This is the newer `include` function, not the preprocessor directive.) See the docs: http://ejs.co/#docs
