### ISSUE TITLE
Please provider correct line number for <% include file %>

### ISSUE THREAD

**Issue by dgofman** [tj/ejs#212]
It's so hard to debug and analyze error message in the console if template using multiple <% include 
%> sub-templates. It's working only when no extra lines in the code. However any empty lines or comments  will cause invalid reference in the console:

Example: 
### body.html

``` javascript
<p><%= this_variable_is_not_defined %></p>
```

```
ReferenceError: index.html:6
   1| <html> 
   2| <head> 
   3| <% include header.html %> 
   4| </head> 
   5| <body> 
>>   6| <% include body.html %> 
```

this_variable_is_not_defined is not defined

Now add couple lines into body.html:
### body.html

``` javascript
<!-- REMOVE THIS LINE -->
<p><%= header %></p>
<p><%= this_variable_is_not_defined %></p>
```

```
ReferenceError: index.html:3
   1| <html> 
   2| <head> 
>> 3| <% include header.html %> 
   4| </head> 
   5| <body> 
   6| <% include body.html %> 
```

Why is line 3 (index.html -> header.html) ? The error still on line 6 in "index.html" or on line 3 in "body.html"

Some workaround: 
Update node_modules\ejs\lib\ejs.js 
Line 505

``` javascript
generateSource: function () {
    var self = this
      , matches = this.parseTemplateText()
      , d = this.opts.delimiter;

    if (matches && matches.length) {
    this.source = '    ; __filename = "' + this.opts.filename.replace(/\\/g,  '/') + '"\n';
```

Now result will be:

```
ReferenceError: body.html:3
   1| <html> 
   2| <head> 
>> 3| <% include header.html %> 
   4| </head> 
   5| <body> 
   6| <% include body.html %> 
```

At least I know an invalid file name (body.html) and line number, but we need to fix output of "index.html" or display source of "body.html". 

Please can some one fix that issue.

Other files:
### header.html

``` javascript
<title><%= header %></title>
```
### index.html

``` javascript
<html>
<head>
<% include header.html %>
</head>
<body>
<% include body.html %>
</body>
</html>
```
### index.js

``` javascript
var express = require('express'),
    ejs = require('ejs');
var app = express();
app.engine('.html', ejs.__express);
app.set('view engine', 'ejs');
app.get('/', function(req, res){ 
    res.render('./index.html', {header: 'Hello EJS'});
});
var server = app.listen(3000, function () {
  console.log('Example app listening at http://localhost:3000');
});
```

**Comment by mde** [comment]
This is not the current version of the project. This one is no longer maintained. The current EJS is here: https://github.com/mde/ejs

As I mentioned previously (here: https://github.com/mde/ejs/issues/119), I would be happy to consider merging a pull request that implements this fix.

**Comment by dgofman** [comment]
I am using ejs but problem still exists

**Comment by edilsonvilarinho** [comment]
http://ejs.co/
Index
```
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%- include('partials/title'); %>
```
http://localhost:3000/
```
Error: C:\WorkSpace\umbler\codeingnite-com-gitlab-branch-functionality-1jsRBAE2\app\views\login\login.ejs:6
    4|   <meta charset="utf-8">
    5|   <meta http-equiv="X-UA-Compatible" content="IE=edge">
 >> 6|   <%- include('partials/title'); %>
    7|   <!-- Tell the browser to be responsive to screen width -->
    8|   <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    9|   <!-- Bootstrap 3.3.7 -->
```
server.js
`app.use(express.static('./app/public'));`

|--views
|---partials
|------title.ejs
