### ISSUE TITLE
Some basic question

### ISSUE THREAD

**Issue by EasonWang01** [tj/ejs#214]
I'm new to ejs,there are some question that I would like to know.

1.what's the difference between this two?
   1.new EJS({url: '../partials/header.ejs'}).render();
   2.<% include ../partials/header  %>

2.I download the ejs_1.0_dev.zip from http://www.embeddedjs.com/ but there are three js files which one should I include?

3.I saw an issue from this https://github.com/tj/ejs/issues/93     

```
<%- include(someVar, someObj) %>

app.get('/', function(req, res) {
    res.render('template', {
        someVar: 'partials/index.ejs',
        someObj: {
            name: 'Bruno Krebs'
        }
    });
});
```

Is this works?  
4.Can I pass variable into an include tag like below?

```
<script>
    var as = '../partials/header'
</script>
      <% include as  %>
```

If not ,how can I do this?

5.I can do this in Handlebars,could I do the same in ejs?(click button to change rendered data)

```
 $('.content-placeholder').html(theTemplate(context));
<button style="width:50px;height:50px"onclick="$('.content-placeholder').html(theTemplate(context1))"  > </button>
```

Thanks

**Comment by gamelaster** [comment]
http://www.embeddedjs.com/ are not same as https://github.com/tj/ejs/
