### ISSUE TITLE
Why Cannot <%include [string]%> For Dynamic Including?

### ISSUE THREAD

**Issue by endlessdev** [tj/ejs#220]
Hello, Everyone. I'm going to using ejs include for dynamic including.
But cannot including through variables.

**Sending data to ejs**

``` js
exports.index = function (req, res) {
    res.render('partials/static', {
        page: 'index',
        asset: [
            {type: "css", path: "/css/index.css"}
        ],
        generateAssets,
        content: '../page/index.ejs'
    });
};
```

**In ejs**

``` ejs
<% include content %>
```

I found partial() method.

> <%= this.partial({url: 'templates/partial.ejs'}) %>

But, it doens't work.

It changed partial() method to include look like that.
Why include cannot for dynamic including in ejs? 
Please tell me why or other solution.
Thank you and sorry for my poor English.

**Comment by bruce965** [comment]
```
<%- include(myVariable) %>
```

**Comment by mde** [comment]
This version of EJS is not maintained. The repo is only here for historical reference. The current version is here:

https://github.com/mde/ejs

In the current version, the preprocessor directive style of include is deprecated. You should be using the function-call style, as @bruce965 indicated.
