### ISSUE TITLE
for...in loop not printing correctly.

### ISSUE THREAD

**Issue by khatekar** [tj/ejs#222]
I am using "2.3.4" version.

Here is an example in ".ejs" template and its output

<%_
  var test = ['test1', 'test2', 'test3', 'test4']
  for (var id in test) {
  _%><tr><%_
    if (~~id === 0) {
      _%><td> This Is A Test Title going only Once</td><%_
    } else {
      _%><td> &nbsp;&nbsp;</td><%_
    }
    _%>
    <td> <%= test[id] %><br /></td></tr>
    <%_
  }
_%>

Here is the output >>

This Is A Test Title going only Once  
                                                             test1
                                                        test2
                                                           test3 
                                                           test4
This Is A Test Title going only Once   function () { return this[this.length - 1]; }
This Is A Test Title going only Once  function (i) { return this[this.length - (1 + i)]; }

Not sure if I had a bug here, but why it prints the last two lines, can anyone help please?

**Comment by khatekar** [comment]
I missed to use "hasOwnProperty". I fixed it.

**Comment by mde** [comment]
Also, this repo is no longer maintained. v2 of EJS is here: https://github.com/mde/ejs
