### ISSUE TITLE
EJS include error

### ISSUE THREAD

**Issue by zeroN1** [tj/ejs#230]
Hi,

I am trying to include some helper functions for ejs in my view file that I have written. I have tried:
`<% include helpers.ejs %>`
Then, in my view file:
`<% module_start('$body', [{name:'display', value:'block'}], 'body'); %>`
However, I end up with the following error:
`Reference Error: module_start is not defined`
How do I fix this?

**Comment by mde** [comment]
This version of EJS is no longer supported. The current version is here: https://github.com/mde/ejs
