### ISSUE TITLE
var not defined, needs to use locals before the variable. (Using express)

### ISSUE THREAD

**Issue by pipegreyback** [tj/ejs#232]
Hi there, I am using EJS as view engine for an express app, I am having the following issue: Whenever I want to use a variable on EJS, I got an error telling me that that variable is not defined, in order to solve this, I have to put `locals` before the variable, I don't know if this is some config problem or what, but I have been trying to look for an answer and haven't got one yet. The funny-sad thing, is that after I use the `locals` stuff, I can render the ejs with no problem, but the expected output does not appear, so I am not getting render erros, but I my variables aren't showing up neither.

Some of my code:
```
//app.js
var expressLayouts = require('express-ejs-layouts');
//...
	app.set('view engine', 'ejs');
	app.engine('html', require('ejs').renderFile);
	app.use(expressLayouts);
...
```

```
//layouts.ejs
        <ul class="nav nav-pills float-right">
          <% if(locals.user){%>   //-> As you may see here, If I dont use locals before user, I got the 'user' is undefined
            <li class="nav-item">
              <a class="nav-link" href="/">Dashboard <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users/logout">Logout</a>
            </li>
            <% }else{ %>
              <li class="nav-item">
                <a class="nav-link" href="/users/login">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/users/register">Register</a>
              </li>
              <% } %>
        </ul>
```
```
//register.ejs
<h2 class="page-header">Register</h2>
<% if(locals.errors){ %>
	<% errors.forEach(function(err){ %>
		<div class="alert alert-danger">
		<p>
		<%=err.msg%>
		</p>
		</div>
		<% });%>
<%}%>
```
So I don't know if this is a issue from my ejs config, or from my way of passing the variables from the controller.

**Comment by dev2games** [comment]
It would be awesome if EJS could support handling objects that might or might not be defined. I've been moving my project from Handlebars to EJS, and since the the database is schemaless there are a lot of situations where a certain object might not be defined for one account, but can be for another. Writing the below code is just cumbersome and annoying especially when you're trying to get work done quickly

```
<% if (typeof(object) !== 'undefined' && object.randomProperty && object.randomProperty.someName) { %>
<%= object.randomProperty.someName %>
<% } %>
```
 
In Handlebars, this is the equivalent

```
{{#if object.randomProperty.someName}}
{{ object.randomProperty.someName }}
{{/if}}
```

In Handlebars you can even go as far as just writing

```
{{ object.randomProperty.someName }}
```

And if it doesn't exist, then it just won't print anything.

**Comment by ut-01** [comment]
I'm having similar troubles. It's really distracting from the actual project. Can anyone explain the concept of `locals` or suggest some link.

**Comment by mde** [comment]
This is an outdated version of EJS. It is not the one on NPM. The correct version is here: https://ejs.co/
