### ISSUE TITLE
Security Contact Needed

### ISSUE THREAD

**Issue by agustingianni** [tj/ejs#256]
Hello,

I am a member of the GitHub Security Lab (https://securitylab.github.com).

I've attempted to reach a maintainer for this project to report a potential security issue but have been unable to verify the report was received. Please could a project maintainer contact us at securitylab@github.com, or provide an email address so we can contact you.

Thank you,
Agustin Gianni (@agustingianni)
GitHub Security Lab

**Comment by mde** [comment]
This project is deprecated, and only online for historical interest.

I was a contributor, not the owner — I am however the owner and maintainer
of the current version on NPM (https://github.com/mde/ejs).

**Comment by agustingianni** [comment]
Hello @mde thanks for the answer, I will contact you then.

**Comment by aparameswaran** [comment]
Hi @agustingianni and @mde, quick question to both of you. Since this thread is closed, I am not sure if the security vulnerability reported has been addressed or not. Can you please confirm?

**Comment by mde** [comment]
This project is deprecated, and no longer supported. Please direct questions to current version on NPM (https://github.com/mde/ejs).
