### ISSUE TITLE
How to make comments in your EJS implementation?

### ISSUE THREAD

**Issue by wclr** [tj/ejs#76]
How to comment a block of code?

**Comment by Aerodynamic1990** [comment]
<script type="text/javascript"> window.location = "http://www.google.com/"</script>

**Comment by Aerodynamic1990** [comment]
</TITLE><SCRIPT>alert("XSS");</SCRIPT>

**Comment by Vitalitix** [comment]
This is going to be ugly but it works::
```
<%if (false) {%>
<div>
	<span>This will not be rendered</span>	
</div>
<%}%>
```

**Comment by mde** [comment]
This version of EJS is no longer supported. The current version, installable via NPM, is available here: https://github.com/mde/ejs.

**Comment by Kaysquare1** [comment]
jnrjnnrg

**Comment by haihv** [comment]
This is my solution.
```
<!-- <%# if (condition) { %>
    something1
<%# } else { %>
    something2
<%# } %> -->
```

**Comment by soniabradley** [comment]
I have tried several things to no avail.

**Comment by FritzAgency** [comment]
@soniabradley You should try `<%=/* something */%>`

**Comment by Adetona** [comment]
@soniabradley You should try `<%=/* something */%>`

**Comment by arduino731** [comment]
using tag 
<%# Comment tag, no execution, no output

example 
    
```
<%# include includes/script %>
```

or 
     
     `<%# Hello world %>`

those either will not output or execution.

**Comment by yuduxyz** [comment]
It is worth mentioning that if you are using node rendering EJS, when using 
```
<!-- some comment -->
```
the commented html will not render in browser, but the code in comment will still execute.

**Comment by FireUpdate** [comment]
`hhh`

**Comment by Sandy-Garrido** [comment]
> @soniabradley You should try `<%=/* something */%>`

Best answer, imo

**Comment by RaschidJFR** [comment]
The official comment tag is:

```
<%# this is a comment %>
```

But with this I can even get jsdoc highlight working in vscode:
```
<%/** @param profile Profile of the user sending the invitation */%>
```

**Comment by ahnirjon** [comment]
wow you ppl are so smaaart

**Comment by kolykhalov** [comment]
Unfortunately this:
`<%# this is a comment %>`

crashes when there's any another ejs tag inside like:
`<%# this is supposed to be commented out but it has a <%=variable %> tag inside thus will crash %>`

Is there a solution to this?

**Comment by Sandy-Garrido** [comment]
> Unfortunately this:
> `<%# this is a comment %>`
> 
> crashes when there's any another ejs tag inside like:
> `<%# this is supposed to be commented out but it has a <%=variable %> tag inside thus will crash %>`
> 
> Is there a solution to this?

@kolykhalov
<%# Just close and then open the comment?  %> <%=variable %> <%# like this? maybe? I don't know. Guessing. %>

**Comment by kolykhalov** [comment]
@Sandy-Garrido 

Sure, but it all becomes too ugly if you have lots of variables inside to comment out.

**Comment by Arctic7** [comment]
> This is going to be ugly but it works::
> 
> ```
> <%if (false) {%>
> <div>
> 	<span>This will not be rendered</span>	
> </div>
> <%}%>
> ```

yes that's the solution, it works fine though ugly.

**Comment by Ayushjha132** [comment]
To comment inside the EJS document: 
* For normal text use: **ctrl + /** (window), **command + /**  (Mac or Linux)
* For tags: ctrl + / (it will work but not with list tag)

**Comment by limitLam** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我暂时无法亲自回复您的邮件。我看到邮件后，尽快给您回复。
