### ISSUE TITLE
Using "if" to check variable before usage results in Error, Undefined

### ISSUE THREAD

**Issue by netpoetica** [tj/ejs#90]
From the example in the README

```
<% if (user) { %>
    <h2><%= user.name %></h2>
<% } %>
```

This code, in all situations, always results in an error if you don't pass the data to the file. I am trying to use it as, let's say, a report about whether your password was valid - if it wasn't I would render the file with 

```
res.render('login', { msg: "Error: your password has too many characters." });
```

But if the user were going to the login page and it hadn't yet been posted, I would just use:

```
res.render('login');
```

I could fix this by explicitly sending a msg = null to all routes, but I think that is silly.

Any advice on how to properly handle this? My guess is that what I am doing is somehow unconventional in node/ejs.

Thanks a bunch,
- Keith

**Comment by Focx-o** [comment]
Both types are object and values are same but for some reason not able to equalise. Its always goes to else part.
`<% if(post[0].category_id == cate._id){ %>`

**Comment by fofe00** [comment]
it is better to  use 

<% if(typeof variable=='undefined)
{
your code........
}
%>

**Comment by pierreburton91** [comment]
I'm actually having the same issue as @netpoetica.
Trying to render a template while not initializing a variable.
The check described works, but the template engine still looks through my statement and returns errors when outputing data.

```
 <% if (typeof article != undefined) {%> // Should not be rendered if article var is not passed to template

 >> 23|         <input type="text" value="<%= article.headline %>" />

    24|     <%} else {%>

article is not defined
```

**Comment by trevorobrien** [comment]
It might be your syntax <% if (typeof locals.article !== 'undefined') { %> - pay attention to your operator syntax, != vs !== 

Also because the variable may not exist use locals.

**Comment by ghost** [comment]
> For your `if` statement you need to use `typeof`:
> 
> ```
> <% if (typeof user == 'object' && user) { %>
> ...
> <% } %>
> ```
> The same is actually true of undefined variables in regular JavaScript.

You should better use:
```
<% if (typeof user != 'undefined') { %>
...
<% } %>
```

**Comment by MANOJ-M-01** [comment]
<div> 
            <% if(typeof text !='undefined')  { %>
                <% text.forEach(function(data) { %>
                     <div> Id:<%= data.id %></div>
                     <div> Title:<%= data.title %></div>
                     <div> Body:<%= data.body%></d>
                <% }); %> 
            <% } %>
    </div>

**Comment by cerpins** [comment]
Is it OK to use a shorthand with `this`?

This seems to work
`this?.user?.value`

This will probably also work
`this?.user && user.forEach(function () { ... })`

**Comment by limitLam** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我暂时无法亲自回复您的邮件。我看到邮件后，尽快给您回复。
